service: GoAWSBilling
frameworkVersion: ">=1.48.0"

provider:
  name: aws
  stage: dev
  runtime: go1.x
  region: ap-northeast-1


functions:
  mackerel:
    handler: main
    role: GoAWSBilling
    timeout: 15
    description: Post Metrics to Mackerel for aws const
    memorySize: 128
    environment:
      TZ: Asia/Tokyo
      MKRKEY: ${opt:mkrkey}
    events:
      - schedule: rate(20 minutes)


resources:
  Resources:
    GoAWSBilling:
      Type: AWS::IAM::Role
      Properties:
        RoleName: GoAWSBilling
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        Policies:
          - PolicyName: GoAWSBilling
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource: "*"